### ISSUE TITLE
Improve `append` functionality in mpc-circuits

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#5]
The `CircuitBuilder` API facilitates circuit composition via the `append` method, which copies the gates of the appended circuit. Though it works and is simple, it is quite inefficient and results in a large memory footprint for more complex circuits. Rather than copying the gates in, I propose we modify the append method to take an `Arc<Circuit>`. The new circuit will hold these references instead of copying the gates.

Following this we modify the `Circuit` API, where instead of 
```rust
pub fn gates(&self) -> &[Gate] { .. }
```
we return an iterator:
```rust
pub fn gates(&self) -> impl Iterator<Item = &Gate> { .. }
```

This iterator handles traversing the gates of the circuit (and any appended circuits).

One slight complication is handling constant wires. Our current implementation factors gates with constant wires out, this iterator would ideally do the same. It would have some interactions with circuit statistics, eg `and_count`, so we'd have to sort out what to do there as those stats would change depending on constant inputs to the circuit.

These changes would make the `CircuitBuilder` API more performant, reduce memory consumption and caching complexity.

**Comment by th4s** [comment]
## Conclusion
After having a closer look, it turns out that a "naive" approach does not yield the anticipated performance gains. The current approach can be found on [this branch](https://github.com/privacy-scaling-explorations/mpz/tree/append_circuits3).

While the build time for our circuits nearly vanishes, the overhead from dynamically linking circuit gates is too big, so that in the end this approach is not faster than just copying the gates.

### Some numbers (from my machine):
| task | dev | append_circuits3 |
| --- | --- | --- |
| build_sha256 | 140 ms | < 1 ms |
| compute_sha256 | 3 ms | 23 ms |
| build + compute prf (TLSN repo) | 270 ms | 585 ms | 

Closing this issue.
